export enum EErrorTypes {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  NON_ETHEREUM_BROWSER = 'NON_ETHEREUM_BROWSER',
  WEB3_ACCESS_REJECTED = 'WEB3_ACCESS_REJECTED',
  WEB3_NOT_INITIALISED = 'WEB3_NOT_INITIALISED',
  WEB3_NO_ACCOUNT_FOUND = 'WEB3_NO_ACCOUNT_FOUND'
}
